### ISSUE TITLE
Feature Request: Highlighting inbound / upstream connections.

### ISSUE THREAD

**Issue by vr00n** [28mm/blast-radius#12]
When clicking on a particular entity, it highlights all the outbound (downstream) connections but excludes all the inbound (upstream connections). 

Any particular reason you chose to do this?

Perhaps you could have a toggle where users can choose whether to highlight:
- [ ] Inbounds Only.
- [ ] Outbounds Only.
- [ ] Inbounds and Outbounds.

**Comment by 28mm** [comment]
Hi @vr00n 

You're right: It would definitely be useful to highlight dependent/upstream resources as well as downstream/dependencies. There isn't a compelling reason for the current configuration, except that tooltips would occlude the upstream portion of the graph.

I think this will be a reasonable approach:

 * 1st click (and mouseover): highlight downstream connections, only + tooltip
 * 2nd click: highlight upstream and downstream connections + no tooltip
 * 3rd click: return to normal (no-selection/highlights)

And a further consideration:

 * When showing both upstream and downstream connections, there will need to be some way of identifying which node is selected. Maybe a halo effect or something like that. tbd. 

Thanks for bringing this up!

**Comment by 28mm** [comment]
@vr00n 

Pushed a partial solution (available as v0.1.8 on PyPi)  
 * mouse events work as described above
 * no halo-effect yet for the selected node
 * updated the examples at https://28mm.github.io/blast-radius-docs/ to use the new javascript.

**Comment by vr00n** [comment]
Awesome - Thanks for the fast fast feature!
