### ISSUE TITLE
Possibly to display only partially graph?

### ISSUE THREAD

**Issue by AnthonyWC** [28mm/blast-radius#27]
This is a question; with terraform it is possible to display specific resource/module by using the target feature with plan, e.g:

```
terraform plan -target=resource.foo -o=plan.tfplan
terraform graph -verbose plan.tfplan | dot -Tpng > graph.png
```

Is that also possible to display only that specific graph with blast-radius?

Currently if I use apply the same specific graph with:
```
terraform graph -verbose plan.tfplan | blast-radius --svg > graph.svg
```

It would still display the entire graph (unlike in graph.png)  (perhaps due to the parsing of the HCL which isn't targeted)

**Comment by 28mm** [comment]
@AnthonyWC 3 options:

1. In `--serve` mode, use the red "prune to subgraph" button
![screen shot 2018-03-01 at 1 47 38 pm](https://user-images.githubusercontent.com/22941656/36871549-701af576-1d57-11e8-9af6-5f237caf7e19.png)
2. use the `--center` argument, to do the same thing from the command line. e.g.
````bash
[...]$ terraform graph           \
         | blast-radius --center \
         "[root] module.us-west-2.module.secondary_subnet.data.aws_vpc.target" \
         --svg
````
3. use the `--focus` argument to show only the specified resource and its dependencies. 
````bash
[...]$ terraform graph          \
         | blast-radius --focus \
         "[root] module.us-west-2.module.secondary_subnet.data.aws_vpc.target" \
         --svg
````

**Comment by elttam-ben** [comment]
Really great feature, should be added to the README.md. It was not immediately apparent to me that it only works with `--svg` (and it also works with `--json`).

I'd like to be able to do focus and not just center in the GUI.
