### ISSUE TITLE
Terraform Version in Docker container

### ISSUE THREAD

**Issue by cscheib** [28mm/blast-radius#33]
The version of Terraform included in the Docker image is relatively old now.  If you are using remote state and a newer version of Terraform, you cannot run blast-radius without editing the Dockerfile, update the  TF_VERSION variable, and building a new image.

I'd like to propose building/maintaining multiple versions of the blast-radius container for x number of current versions of Terraform, and using tags to pull the proper version.

I don't see any CI stuff in the repository, otherwise I'd submit a PR against that.

**Comment by robertpeteuil** [comment]
I agree this would be very useful.

**Comment by 28mm** [comment]
@cscheib @robertpeteuil sounds like a great idea. I'm not super familiar with the options here-between Travis, Circle, and whatever other options Github supports, can you make a recommendation? Many thanks.
