### ISSUE TITLE
Build on Alpine Linux instead of Ubuntu

### ISSUE THREAD

**Issue by skyzyx** [28mm/blast-radius#36]
A utility like this should be as small as possible. Building it on Alpine Linux would be far more favorable than having to download the Ubuntu image.

**Comment by 28mm** [comment]
Agreed. The decision to replace Alpine with Ubuntu was motivated by a rendering issue with the stock Alpine version of Graphviz. Essentially, the "overfull hbox" problem where resource labels were overflowing the boxes drawn around them.

There should be an easy fix for this. PRs accepted.

**Comment by skyzyx** [comment]
Ah. Gotcha. I'll flag this as something to poke at. 👍
