### ISSUE TITLE
No matching distribution found for blast-radius

### ISSUE THREAD

**Issue by vr00n** [28mm/blast-radius#4]
hey there - i get this message when trying to install your amazing tool!
```
pip3 install blast-radius
Collecting blast-radius
  Could not find a version that satisfies the requirement blast-radius (from versions: )
No matching distribution found for blast-radius
```

**Comment by 28mm** [comment]
Hi @vr00n,

I’ve just noticed a typo in the readme. It’s actually BlastRadius in PyPi (camel-case) rather than blast-radius (hyphenated). Facepalm.

On the road right now, but I’ll tweak the docs when I’m back.

Thanks for opening an issue, and brining this up!
