### ISSUE TITLE
init-ed Terraform project?

### ISSUE THREAD

**Issue by vr00n** [28mm/blast-radius#5]
Hi again:

`/path/to/init-ed Terraform project` means what exactly?

Thank you

**Comment by 28mm** [comment]
Hi @vr00n,

blast-radius expects to be run either from within a terraform project directory, in which “terraform init” has been run, or to be given the path to such a directory as a command-line argument

So, either:

    cd terraform-project-dir
    terraform init
    blast-radius —serve

Or

    blast-radius —serve path-to-terraform-project-dir

**Comment by vr00n** [comment]
Thanks @28mm, so if I were following the `example configurations`, say the `open stack` one - https://28mm.github.io/blast-radius-docs/examples/terraform-provider-openstack/app-with-networking/

what is the path to the terraform project dir?

Is it the root directory - https://github.com/terraform-providers/terraform-provider-aws

OR

this one - https://github.com/terraform-providers/terraform-provider-openstack/tree/master/test-infra/standard

?

Thanks again. I'd like to experience the joy of successfully building one of these diagrams with an admittedly limited knowledge of terraform, which I am currently grokking further.

**Comment by 28mm** [comment]
Aha, I think I see. That particular example comes from here:

    https://github.com/terraform-providers/terraform-provider-openstack/tree/master/examples/app-with-networking

You’d have to clone that repository, and initialize the example:

    cd terraform-provider-openstack/examples/app-with-networking
    terraform init
    blast-radius --serve

Hope that helps!

**Comment by vr00n** [comment]
That does Patrick. Thank you! V. excited to play around with this! Also a great service for mildly dyslexic devops folks who rely on visually parsing the world around them.
