### ISSUE TITLE
Getting chmod: cannot access

### ISSUE THREAD

**Issue by kiplphp38** [28mm/blast-radius#52]
i download the zip code and extract. put one *.tf file in same directory. after running the below command, i got error mentioned below:
command:
```
docker build -t blast-radius - < Dockerfile
```
error:
```
chmod: cannot access './docker-build.sh': No such file or directory
```

**Comment by 28mm** [comment]
@kiplphp38 are you trying to build the docker image, or run it? I would not place terraform files in the blast-radius source directory, as it doesn't look for them at build time.

To build the image:

````bash
docker build -t blast-radius .
````

To run it, change to the project directory, and run:

````bash
docker run --cap-add=SYS_ADMIN -it --rm -p 5000:5000 -v $(pwd):/workdir:ro 28mm/blast-radius
````

Hope that helps!

**Comment by kiplphp38** [comment]
@28mm 
I successfully build the image but got another error
To build the image:
`docker build -t blast-radius .`

To run it in the same directory having *.tf files with modules. i got error
`/src/docker-entrypoint.sh: line 14: cd: /workdir-rw: No such file or directory`

then i update /workdir to /workdir-rw in the below command
`docker run --cap-add=SYS_ADMIN -it --rm -p 5000:5000 -v $(pwd):/workdir-rw:ro 28mm/blast-radius`

after that i got error:
`Error loading modules: error downloading 'file:///workdir-rw/modules/vpc': remove .terraform/modules/9bf8ac2d543bbd59da3f80f814aabc34: read-only file system`
