### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by 28mm** [28mm/blast-radius#7]
@brogersyh -- just merged your changes from #6 . Really wonderful stuff. I'm a faltering and infrequent user of `docker`, but managed to upload to the docker hub under `28mm/blast-radius`, and will make this part of the release process. 

Cutting an issue for discussion.

  * Sometimes label text overflows its bounding box. I suspect this is to do with the fonts Graphviz uses under the alpine linux image being differently sized/proportioned than on macos.
  * `docker-entrypoint.sh` runs `terraform init`. If a `.terraform` directory already maybe it should run `terraform get`, instead? 
  * Documentation. I've got some other changes planned in this area, so I'll probably tackle this soon.

Anyway, would be glad to have your thoughts, and happy new years 🥂

**Comment by brogersyh** [comment]
Re fonts - changed to from alpine to ubuntu and this resolved it, at least on my simple example (now renders correction as for MacOS), I've submitted another PR - although it makes the image bigger, doesn't matter much at this stage.

Terraform init vs. get - will think about this more as i apply it to my project over the coming days

Thx for putting this together, I think it has a lot of potential, will let you know how it is working for my scenarios

br

**Comment by brogersyh** [comment]
I've noticed occasionally a request (when in --serve mode) doesn't render - another request immediately after does. When this occurs, there is only the HTTP GET command in the log, nothing after.

**Comment by 28mm** [comment]
* merged #8 switching to Ubuntu.
  * added a note about the docker image to the README/quickstart

Haven't yet replicated the issue of failed requests that you describe. Looking to add some tests with `curl` and `chromedriver`, to hopefully uncover this sort of issue.
