### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by clebio** [28mm/blast-radius#89]
I love this tool, and have been a fan of blast-radius for a while (even sent in #41 way back when). Looking over open issues, it doesn't seem like there's been much activity from @28mm  in a while. Meanwhile recent versions of Terraform appear to be incompatible.

Is the project still actively maintained? Patrick, do you want some help with that?

**Comment by jeacott1** [comment]
@clebio it looks bleak.

**Comment by clebio** [comment]
I reached out to @28mm by email and discussed this a bit. I'll see what I can do to burn down some of the backlog, when I have time.
